### ISSUE TITLE
Peatio blockchain error

### ISSUE THREAD

**Issue by streetcrypto7** [rubykube/peatio#2288]
```
{"level":"ANY","time":"2019-08-01 04:00:48","message":"#<Peatio::Blockchain::ClientError: \n-- 401 Unauthorized --\n\n-- Request URL --\nhttp://cpuchaind:19707/\n\n-- Request method --\nPOST\n\n-- Request headers --\n{\"User-Agent\":\"Faraday v0.15.4\",\"Accept\":\"application/json\",\"Content-Type\":\"application/json\"}\n\n-- Request body --\n{\"jsonrpc\":\"1.0\",\"method\":\"getblockcount\",\"params\":[]}\n\n-- Response headers --\n{\"www-authenticate\":\"Basic realm=\\\"jsonrpc\\\"\",\"date\":\"Thu, 01 Aug 2019 04:00:48 GMT\",\"content-length\":\"0\",\"content-type\":\"text/html; charset=ISO-8859-1\"}\n\n-- Response body --\n\n>"}
{"level":"ANY","time":"2019-08-01 04:00:48","message":"/home/app/lib/peatio/bitcoin/blockchain.rb:35:in `rescue in latest_block_number'\n/home/app/lib/peatio/bitcoin/blockchain.rb:32:in `latest_block_number'\n/home/app/app/services/blockchain_service.rb:17:in `block in latest_block_number'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache.rb:323:in `block in fetch'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache.rb:694:in `block in save_block_result_to_cache'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache.rb:663:in `block in instrument'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache.rb:663:in `instrument'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache.rb:693:in `save_block_result_to_cache'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache.rb:323:in `fetch'\n/home/app/app/services/blockchain_service.rb:16:in `latest_block_number'\n/home/app/app/workers/daemons/blockchain.rb:20:in `process'\n/home/app/app/workers/daemons/blockchain.rb:9:in `block (2 levels) in run'"}
{"level":"WARN","time":"2019-08-01 04:00:48","message":"Error: \n-- 401 Unauthorized --\n\n-- Request URL --\nhttp://cpuchaind:19707/\n\n-- Request method --\nPOST\n\n-- Request headers --\n{\"User-Agent\":\"Faraday v0.15.4\",\"Accept\":\"application/json\",\"Content-Type\":\"application/json\"}\n\n-- Request body --\n{\"jsonrpc\":\"1.0\",\"method\":\"getblockcount\",\"params\":[]}\n\n-- Response headers --\n{\"www-authenticate\":\"Basic realm=\\\"jsonrpc\\\"\",\"date\":\"Thu, 01 Aug 2019 04:00:48 GMT\",\"content-length\":\"0\",\"content-type\":\"text/html; charset=ISO-8859-1\"}\n\n-- Response body --\n\n. Sleeping for 10 seconds"}
```

While I can connect them with curl and bitcoin-cli, the problem only occurs with `microkube_blockchain` daemon.

**Comment by streetcrypto7** [comment]
Wallet address generation works fine, but the blockchain doesn't work

**Comment by streetcrypto7** [comment]
Very odd but you should first disable the blockchain and change them to active, I will check the MySQL scheme probably my fault 😂

**Comment by streetcrypto7** [comment]
Now more odd situation

```
{"level":"INFO","time":"2019-08-01 05:55:29","message":"Processing CPUchain blocks."}
{"level":"DEBUG","time":"2019-08-01 05:55:29","message":"  Blockchain Load (0.3ms)  SELECT  `blockchains`.* FROM `blockchains` WHERE `blockchains`.`id` = 3 LIMIT 1"}
{"level":"INFO","time":"2019-08-01 05:55:29","message":"Skip synchronization. No new blocks detected, height: 36330, latest_block: 36340. Sleeping for 10 seconds"}
{"level":"INFO","time":"2019-08-01 05:55:39","message":"Processing Bitcoin blocks."}
{"level":"DEBUG","time":"2019-08-01 05:55:39","message":"  Blockchain Load (0.4ms)  SELECT  `blockchains`.* FROM `blockchains` WHERE `blockchains`.`id` = 2 LIMIT 1"}
{"level":"INFO","time":"2019-08-01 05:55:39","message":"Skip synchronization. No new blocks detected, height: 1571862, latest_block: 36340. Sleeping for 10 seconds"}
```

![캡처](https://user-images.githubusercontent.com/52137633/62269048-d8e71000-b46c-11e9-9c17-2b53572c536b.PNG)

Bitcoin is referring CPUchaind 😂

**Comment by streetcrypto7** [comment]
I think it is fixed on https://github.com/rubykube/peatio/pull/2243
